# Generated by Django 5.2.5 on 2025-08-12 08:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='harga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='produk',
            name='tanggal_dibuat',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
