# Generated by Django 5.2.4 on 2025-08-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0002_produk_harga_produk_tanggal_dibuat'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='sales_count',
            field=models.IntegerField(default=0),
        ),
    ]
