# Generated by Django 5.2.4 on 2025-08-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0003_produk_sales_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='detail_produk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produk',
            name='spesifikasi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produk',
            name='ukuran',
            field=models.TextField(blank=True, null=True),
        ),
    ]
